name: GLuaFixer

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  gluaLint:
    uses: FPtje/GLuaFixer/.github/workflows/glualint.yml@master
    # runs-on: ubuntu-20.04
    # steps:
    #   - uses: actions/checkout@v2
    #   - run: wget https://github.com/FPtje/GLuaFixer/releases/download/1.22.0/glualint-1.22.0-linux.zip
    #   - run: unzip glualint-*.zip
    #   - run: ./glualint --output-format github lint .
